### ISSUE TITLE
how to compress a text with a language model?

### ISSUE THREAD

**Issue by ArlanCooper** [google-deepmind/language_modeling_is_compression#3]
thanks for your great work!
i have a small question to ask.
can you give me a demo,which shows the way to use a language model to compress a text and decompress?
thanks

**Comment by anianruoss** [comment]
* Install and set up the repository as described in the [README](https://github.com/google-deepmind/language_modeling_is_compression#installation)
* Run `train.py` to train a small language model
* Run the following example code:
```python
length = 32
data = random.randbytes(length)
compressed_data, num_padded_bits = language_model.compress(
  data,
  return_num_padded_bits=True,
  use_slow_lossless_compression=True,
)
decompressed_data = language_model.decompress(
  compressed_data,
  num_padded_bits=num_padded_bits,
  uncompressed_length=length,
)
assert data == decompressed_data
print('compression rate', len(compressed_data) / len(data))
```

Note that, due to numerical issues, when trying to compress and decompress, one needs to compute the token's `pdf`s separately for every proper subsequence of the input sequence. This has a time complexity of `O(n^2)` (whereas computing the `pdf`s in a single go is `O(n)`). See `compressors/language_model.py` for the implementational details.

**Comment by ArlanCooper** [comment]
thank you
