### ISSUE TITLE
Confirm the chunked compression rate

### ISSUE THREAD

**Issue by machao23** [google-deepmind/language_modeling_is_compression#4]
We've follow the steps on README (`python train.py` and `python compress.py --compressor=language_model`), the chunked compression rate is `86.1`, is that expected since the paper said language model could reach up to `8.3`.

**Comment by anianruoss** [comment]
The compression rate of `8.3` on enwik9 corresponds to Chinchilla 70B (https://arxiv.org/abs/2309.10668), which is significanly larger than the model that you train with `train.py`, which is only trained on `enwik` data (instead of _MassiveText_) and only consists of `231936` parameters.

Thus, you should aim to replicate the compression rate of the `Transformer 200K` model, i.e., `30.9`, by training for the same amount of steps (i.e., 1 million steps instead of `100`)
